export default  
new Object({
    "container-width":1100,
    "block":[
        {
            "id":"row-block-1",
            "display":"flex",
            "flex-direction":"column",
            "order":"asc",
            "flex-group":3,
            "items":[
                {
                    "id":"item-row-1",
                    "width":"307",
                    "height":"215",
                },
                {
                    "id":"item-row-2",
                    "width":"375",
                    "height":"292",
                },
                {
                    "id":"item-row-3",
                    "width":"345",
                    "height":"204",
                },
            ],
       },
        {
            "id":"row-block-2",
            "display":"flex",
            "flex-direction":"column",
            "order":"asc",
            "flex-group":2,
            "items":[
                {
                    "id":"item-row-1",
                    "width":"355",
                    "height":"358",
                },
                {
                    "id":"item-row-2",
                    "width":"120",
                    "height":"188",
                },
            ],
        },
        {
            "id":"row-block-3",
            "display":"flex",
            "flex-direction":"row",
            "items":[
                {
                    "id":"item-row-1",
                    "width":"50",
                    "height":"2",
                },
                {
                    "id":"item-row-2",
                    "width":"130",
                    "height":"30",
                },
                {
                    "id":"item-row-3",
                    "width":"50",
                    "height":"2",
                },
            ],
        },
        {
            "id":"row-block-4",
            "display":"flex",
            "flex-group":3,
            "flex-direction":"column",
            "order":"desc",
            "justify-content":"left",
            "item-repeat":4,
            "items":
            {
                "id":"item-row",
                "width":"314",
                "height":"228",
            }
        },
    ],
    
})